### ISSUE TITLE
Abnormal display of title style in editing mode

### ISSUE THREAD

**Issue by canxer314** [Bad3r/Logseq-Nord-Theme#11]
## normal:

<img width="718" alt="image" src="https://github.com/Bad3r/Logseq-Nord-Theme/assets/4979384/a2adbc7f-e466-4a47-b243-1d8cfc9d6d05">

## edit:
<img width="483" alt="image" src="https://github.com/Bad3r/Logseq-Nord-Theme/assets/4979384/61aacac2-4716-4926-92dc-724eebcd2b32">

**Comment by Bad3r** [comment]
Just pushed a fix. Sorry for the delay.
