### ISSUE TITLE
Alternative color schemes?

### ISSUE THREAD

**Issue by kerim** [Bad3r/Logseq-Nord-Theme#3]
Since the flow themes aren't being maintained any more, I'm wondering if it would be possible to offer some alternative color schemes for this? I especially like high contrast themes like the "ark" and "old hope" from flow. Would love to be able to use Nord with these alternative color schemes...

**Comment by Bad3r** [comment]
Hey @kerim, this is not based on the Flow theme. This is based on [Dev theme ](https://github.com/pengx17/logseq-dev-theme) using [Nord color scheme](https://www.nordtheme.com/). Nord is a specific color scheme; therefore, it's not possible to offer other schemes under the name Nord. You might want to try the upstream theme, Dev theme, or the developer theme from the marketplace, which has more color options.

I don't plan to maintain other themes, as the Nord theme is what I use across all my application when possible. Nord only currently comes in dark mode, but I might consider adding a light variant in the future. 

For more information on Nord colors and palettes:
https://www.nordtheme.com/docs/colors-and-palettes
https://github.com/nordtheme
